---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - secrets.yaml
  - postgresql.yaml
  - storage.yaml
  - keycloak-deployment.yaml
  - service-route.yaml

# Common labels
commonLabels:
  app: keycloak

