apiVersion: v1
kind: Service
metadata:
  name: glooscap-operator
  namespace: glooscap-system
  labels:
    app.kubernetes.io/name: operator
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: operator
  ports:
  - name: http-api
    port: 3000
    targetPort: http-api
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  type: ClusterIP

