---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - namespace.yaml
  - secrets.yaml
  - postgresql.yaml
  - redis.yaml
  - storage.yaml
  - migration-job.yaml
  - outline-deployment.yaml
  - service-route.yaml

# Common labels
commonLabels:
  app: outline
  version: "0.83.0"

