# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to wiki.glooscap.dasmlab.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: wikitarget-viewer-role
rules:
- apiGroups:
  - wiki.glooscap.dasmlab.org
  resources:
  - wikitargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wiki.glooscap.dasmlab.org
  resources:
  - wikitargets/status
  verbs:
  - get
