apiVersion: wiki.glooscap.dasmlab.org/v1alpha1
kind: WikiTarget
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: wikitarget-sample
spec:
  # TODO(user): Add fields here
