apiVersion: v1
kind: Service
metadata:
  name: glooscap-ui
  namespace: glooscap-system
  labels:
    app: glooscap-ui
    app.kubernetes.io/name: glooscap-ui
spec:
  selector:
    app: glooscap-ui
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: LoadBalancer

