apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: manual
  name: glooscap-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glooscap-operator-role
subjects:
- kind: ServiceAccount
  name: glooscap-operator
  namespace: glooscap-system

